<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Company>Cyotek Ltd</Company>
    <Product>Cyotek QuickScan</Product>
    <VersionPrefix>1.4.0</VersionPrefix>
    <VersionSuffix></VersionSuffix>
    <Copyright>Copyright © 2019-2026 Cyotek Ltd. All Rights Reserved.</Copyright>
  </PropertyGroup>

  <!--Strong Name-->
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)res\Cyotek.QuickScan.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <!-- https://stackoverflow.com/a/70905904 -->
  <ItemGroup>
    <AssemblyAttribute Include="System.CLSCompliantAttribute">
      <_Parameter1>true</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>